### ISSUE TITLE
Can't build Docker image for Ubuntu 20.04 

### ISSUE THREAD

**Issue by danielvachalek** [lambdal/lambda-stack-dockerfiles#11]
Tried following these instructions: https://lambdalabs.com/blog/set-up-a-tensorflow-gpu-docker-container-using-lambda-stack-dockerfile/

When I run this step
# Build a docker image named lambda-stack:20.04
sudo docker build -t lambda-stack:20.04 -f Dockerfile.focal git://github.com/lambdal/lambda-stack-dockerfiles.git

I get an error message
Errors were encountered while processing:
 /tmp/apt-dpkg-install-vKTQpk/001-libcudnn7_7.6.5-0lambda1_amd64.deb
 /tmp/apt-dpkg-install-vKTQpk/032-libcudnn-dev_7.6.5-0lambda1_amd64.deb

E: Sub-process /usr/bin/dpkg returned an error code (1)
The command '/bin/sh -c apt-get update && 	apt-get install --yes gnupg && 	apt-key add lambda.gpg && 	rm lambda.gpg && 	echo "deb http://archive.lambdalabs.com/ubuntu focal main" > /etc/apt/sources.list.d/lambda.list && 	echo "Package: *" > /etc/apt/preferences.d/lambda && 	echo "Pin: origin archive.lambdalabs.com" >> /etc/apt/preferences.d/lambda && 	echo "Pin-Priority: 1001" >> /etc/apt/preferences.d/lambda && 	echo "cudnn cudnn/license_preseed select ACCEPT" | debconf-set-selections && 	apt-get update && 	DEBIAN_FRONTEND=noninteractive apt-get install 		--yes 		--no-install-recommends 		--option "Acquire::http::No-Cache=true" 		--option "Acquire::http::Pipeline-Depth=0" 	lambda-stack-cuda 		lambda-server && 	rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

**Comment by picekl** [comment]
Hi Daniel, 

I have the same or similar issue. From my experience, there is no working dockerfile offered here. Or a solution to make it build. 

Try to use this image. -- > https://ngc.nvidia.com/catalog/containers/nvidia:tensorflow/tags

Works for me but the performance on the 3080 is quite strange.

Best,
Lukas

**Comment by danielvachalek** [comment]
Thanks, Lukas! I'll give those images a try.

**Comment by simplehx** [comment]
I have the same problem.

**Comment by picekl** [comment]
> Thanks, Lukas! I'll give those images a try.

Let me know if it worked for you. Here are some results from my side (will update it later with more experiments).

2080S vs 3080:
- MobileNet V2 - 10% speed increase.

**Comment by picekl** [comment]
> I have the same problem.

Did you try the official nvidia image?

**Comment by danielvachalek** [comment]
@picekl Thanks again, I was able to get the Nvidia image to run. Now working through linking this image with the fast.ai to make a ready-made fast.ai container.
Edit: clarity

**Comment by picekl** [comment]
@danielvachalek Are you talking about the Lambda or Nvidia image?

**Comment by sclarkson** [comment]
Could you try the most recent version? 30bcae0

**Comment by picekl** [comment]
> Could you try the most recent version? [30bcae0](https://github.com/lambdal/lambda-stack-dockerfiles/commit/30bcae027beac901c2ed7890bacd72df54f9e2ed)

@sclarkson Thanks. This helped. FYI the speed up is the same as for the Nvidia Image. I will try another architecture soon.

**Comment by WAUthethird** [comment]
@danielvachalek Let me know how that goes, fast.ai is my use case and I'd like to use the 3090s on there.

**Comment by danielvachalek** [comment]
I was able to build the docker image and follow the tutorial, thanks all.
