### ISSUE TITLE
Ubuntu 20.04 image not building - cudnn license issue?

### ISSUE THREAD

**Issue by jlphillipsphd** [lambdal/lambda-stack-dockerfiles#9]
I've been trying to build the ubuntu 20.04 based image, but eventually run into the following error:

```
Selecting previously unselected package lambda-stack-cuda.
Preparing to unpack .../480-lambda-stack-cuda_0.1.12~20.04.2_all.deb ...
Unpacking lambda-stack-cuda (0.1.12~20.04.2) ...
Errors were encountered while processing:
 /tmp/apt-dpkg-install-HADSvk/001-libcudnn7_7.6.5-0lambda1_amd64.deb
 /tmp/apt-dpkg-install-HADSvk/032-libcudnn-dev_7.6.5-0lambda1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
The command '/bin/sh -c apt-get update &&       apt-get install --yes gnupg &&  apt-key add lambda.gpg &&       rm lambda.gpg &&        echo "deb http://archive.lambdalabs.com/ubuntu focal main" > /etc/apt/sources.list.d/lambda.list &&      echo "Package: *" > /etc/apt/preferences.d/lambda &&    echo "Pin: origin archive.lambdalabs.com" >> /etc/apt/preferences.d/lambda &&    echo "Pin-Priority: 1001" >> /etc/apt/preferences.d/lambda &&   echo "cudnn cudnn/license_preseed select ACCEPT" | debconf-set-selections &&     apt-get update &&       DEBIAN_FRONTEND=noninteractive          apt-get install                 --yes           --no-install-recommends                 --option "Acquire::http::No-Cache=true"          --option "Acquire::http::Pipeline-Depth=0"              lambda-stack-cuda               lambda-server &&        rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```
I've attached the rest of the build log in case any of the other info there is useful, but it appears that the license for cudnn isn't being pre-seeded as expected? Not sure how to proceed at this point, so any pointers would be appreciated.
[build.log](https://github.com/lambdal/lambda-stack-dockerfiles/files/5534924/build.log)

**Comment by jlphillipsphd** [comment]
Doing a little more digging, I am suspecting the problem is arising from a version mismatch between the library package (libcudnn7) and the license package (cudnn-license).

I have a Lambda Workstation running the Ubuntu 20.04 Lambda Stack, and it reports the following:
```
jphillips@raziel:~/Docker/lambda-stack-dockerfiles$ dpkg-query -l cudnn-license
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version        Architecture Description
+++-==============-==============-============-=============================================================
ii  cudnn-license  8.0.4-0lambda1 all          NVIDIA CUDA deep neural network, run-time libraries (license)
jphillips@raziel:~/Docker/lambda-stack-dockerfiles$ dpkg-query -l libcudnn*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name               Version        Architecture Description
+++-==================-==============-============-===================================================
ii  libcudnn-dev:amd64 7.6.5-0lambda1 amd64        NVIDIA CUDA deep neural network, development files
ii  libcudnn7:amd64    7.6.5-0lambda1 amd64        NVIDIA CUDA deep neural network, run-time libraries
jphillips@raziel:~/Docker/lambda-stack-dockerfiles$ 
```

It appears that the libcudnn7 and libcudnn-dev packages are at version 7.6.5, but the cudnn-license packages is at 8.0.4.

Using this information, I pruned down the Dockerfile to just install libcudnn7 and cudnn-license to allow for quick reproduction of the problem (attached below also with another log of the failed build).
[build-minimal.log](https://github.com/lambdal/lambda-stack-dockerfiles/files/5540226/build-minimal.log)
[Dockerfile.txt](https://github.com/lambdal/lambda-stack-dockerfiles/files/5540230/Dockerfile.txt)

Will report back with more info soon... I think I may be close to working it out.

**Comment by jlphillipsphd** [comment]
I found a workaround that allows the container to build even with the mismatch by setting the exact license for both the v7 packages and the v8 package. The generic license_preseed option is getting accepted by either the v7 or v8, but not both during builds without this approach. So, I've just added them both. The resulting changes are in PR #10 

I understand if this would rather get solved in some other way (such as syncing the versions in the repo eventually) instead of this approach, but at the moment I -really- needed a container for my deployment and this does the job.
